/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actionWithOllama from "../actionWithOllama.js";
import type * as ai from "../ai.js";
import type * as analytics from "../analytics.js";
import type * as assessment from "../assessment.js";
import type * as client from "../client.js";
import type * as decodeVIN from "../decodeVIN.js";
import type * as fileStorage from "../fileStorage.js";
import type * as identity from "../identity.js";
import type * as inventations from "../inventations.js";
import type * as inviteMembers from "../inviteMembers.js";
import type * as invoices from "../invoices.js";
import type * as logFormCompletion from "../logFormCompletion.js";
import type * as organization from "../organization.js";
import type * as selfAssessment from "../selfAssessment.js";
import type * as services from "../services.js";
import type * as vehicles from "../vehicles.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  actionWithOllama: typeof actionWithOllama;
  ai: typeof ai;
  analytics: typeof analytics;
  assessment: typeof assessment;
  client: typeof client;
  decodeVIN: typeof decodeVIN;
  fileStorage: typeof fileStorage;
  identity: typeof identity;
  inventations: typeof inventations;
  inviteMembers: typeof inviteMembers;
  invoices: typeof invoices;
  logFormCompletion: typeof logFormCompletion;
  organization: typeof organization;
  selfAssessment: typeof selfAssessment;
  services: typeof services;
  vehicles: typeof vehicles;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
